[package]
name = "merkle_tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name= "merkle"
path = "./bin/main.rs"


[dependencies]
bytes = "1.10.1"
hex = "0.4.3"
indexmap = "2.9.0"
sha2 = "0.10.1"

[profile.release]
debug = 1
